config/database.yml
=> modify-database_yml

README.md
#What
・メルカリにおける各テーブルの定義
・各テーブルのカラムの定義
・リレーションの定義
#Why
開発にまず必要なデータベースを定義するため。
=> updated Readme to specify Database relationships

app/views/layouts/application.html.erb, app/views/posts/index.html.erb
=> toppage&footer

app/assets/stylesheets/posts.scss, app/views/posts/index.html.erb
トップページのメイン部分の見た目作成
#why
はじめに、最新の出品を表示するため
=> トップページのメイン部分

app/assets/stylesheets/_signup2.scss, app/assets/stylesheets/_signup4.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/mixin/_form.scss, app/views/posts/signup2.html.erb, app/views/posts/signup4.html.erb
#What
・app/views/posts/signup2.html.erb 及びscssの作成
・app/assets/stylesheets/mixin/_form.scssにmixinを追加(submitボタン、 ユーザ登録各ページの中見出し。)
#Why
SMS認証ページを完成させるため。
=> created view for sms authorization

app/assets/stylesheets/_signup3.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/mixin/_form.scss, app/views/posts/signup3.html.erb
#What
・app/views/posts/signup3.html.erb、及びscssの作成
　(都道府県のプルダウンにより、google翻訳が発動する。
　 取り急ぎ3県のみしか登録していない、と不備がありますが、一旦mergeします。) 
#Why
ユーザ住所登録ページ作成のため。
=> created view for address registration

app/assets/stylesheets/signup.header.scss, app/views/posts/_signup.header.html.erb
What
ユーザー登録画面のヘッダーを実装。
恥ずかしながら、他チームの協力で完成させました。
=> signup-header

app/assets/stylesheets/sign-in-sample.scss, app/assets/stylesheets/signup1.scss, app/views/posts/signup0.html.erb, app/views/posts/signup1.html.erb, config/deploy.rb
新規会員登録の「会員情報入力画面」のビュー
（masterにあるヘッダー情報を取り込むための、仮のmerge）
会員登録画面の実装のため。
=> add-view-signup1

app/assets/stylesheets/mixin/_form.scss
会員情報入力画面の生年月日欄のheightの修正。
#why
本番環境でビューが崩れていたため。
=> modify-select-height

app/views/signup/_signup.footer.html.haml
What
_signup.footer.html.hamlのロゴを白からグレーに変換
=> logo change _signup.footer.html.haml

app/assets/stylesheets/application.scss, app/assets/stylesheets/creditCard.scss, app/views/posts/creditCard.html.haml, config/routes.rb
What
ユーザークレジットカード登録ページのコーディング
creditCard.html.haml
creditCard.scss
Why
画面実装完了のため
=> registration.credit

Gemfile, Gemfile.lock, app/controllers/signup_controller.rb, app/views/signup/signup1.html.haml, config/initializers/recaptcha.rb
#What
参考資料に従い、recaptcha機能(私はロボットではありません)をビュー"signup1.html.haml"に追加。
#Why
ユーザー新規登録機能完成のため
参考資料
https://qiita.com/k_tada/items/eee5a3965fb5abadab13
=> added recaptcha to user signup function

app/assets/stylesheets/personal_info.scss, app/views/posts/index.html.haml, app/views/posts/personal_info.html.haml
本人情報登録フォームを作成。
personal_info.haml
トップページのヘッダー、フッターと組み合わせ。
_toppage-header.haml
_toppage-footer.haml
マイページのサイドバーの部分テンプレートと組み合わせ。
_sidebar.haml
任意入力の住所入力機能を実装できるようにビューを作成。
=> Personal information form

app/views/posts/creditCard.html.haml
What
render sideber → render sidebar
Why
エラーの解消のため
=> creditcard

Gemfile.lock, app/models/address.rb, spec/factories/addresses.rb, spec/models/address_spec.rb, spec/models/users.rb
What
ユーザー新規登録、ログインのテストコードの実装
Why
テストを実行するため
=> Login test cord

README.md, app/assets/javascripts/images.coffee, app/assets/javascripts/items.coffee, app/assets/stylesheets/images.scss, app/assets/stylesheets/items.scss, app/controllers/images_controller.rb, app/controllers/items_controller.rb, app/helpers/images_helper.rb, app/helpers/items_helper.rb, app/models/image.rb, app/models/item.rb, db/migrate/20191211105802_create_items.rb, db/migrate/20191211112609_create_images.rb, db/schema.rb, spec/controllers/images_controller_spec.rb, spec/controllers/items_controller_spec.rb, spec/factories/images.rb, spec/factories/items.rb, spec/helpers/images_helper_spec.rb, spec/helpers/items_helper_spec.rb, spec/models/image_spec.rb, spec/models/item_spec.rb
What
item.rb, items_controller, image.rb, image_contoller の作成
Why
これから商品に関する機能を実装していくため
=> Create item,image model&controller

app/assets/stylesheets/_add_payments.scss, app/views/posts/add_payments.html.haml, app/views/posts/creditCard.html.haml, app/views/posts/show.html.haml, config/routes.rb, db/schema.rb
#What
【マークアップ】ユーザークレジットカード登録ページ
について本番環境でビューが崩れていたのでcssを修正。(_add_payments.scss)
#Why
　クレジットカード追加情報入力画面完成のため
=> created views for adding creditcard

app/assets/stylesheets/items.show.scss, app/views/posts/show.html.haml
What
商品詳細ページのコードの修正
Why
商品詳細ページのサーバーサイド作業に向けて修正
=> show.devise

app/assets/stylesheets/mixin/_form.scss, app/assets/stylesheets/signup.header.scss, app/views/signup/_signup.header.html.haml
#What
　新規会員登録時の、ステップバーがページ毎に色変化するよう以下ファイルを変更
　signup.header.scss/_signup.header.html.haml
#Why
　新規会員登録機能完成のため。
=> created stepbar-function

app/assets/stylesheets/_sign.up.header.only.logo.scss, app/assets/stylesheets/_signup.footer.scss, app/assets/stylesheets/_signup0.scss
会員登録画面、及びユーザー本人確認画面で使用しているフッターについて、CSSのbgcとmarginを調整。
フロントエンドを整えるため。
=> 会員登録画面、及びユーザー本人確認画面のフッターCSSの調整

app/assets/stylesheets/_add_payments.scss, app/assets/stylesheets/_creditCard.scss, app/assets/stylesheets/_edit_address.scss, app/assets/stylesheets/_sidebar.scss, app/assets/stylesheets/_toppage-header.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/index.scss, app/assets/stylesheets/signout.scss, app/assets/stylesheets/user.mypage.scss, app/assets/stylesheets/user.profile.scss, app/controllers/application_controller.rb, app/controllers/posts_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/devise/registrations/edit_reference.html.haml, app/views/layouts/_sidebar.html.haml, app/views/layouts/_toppage-header.html.haml, app/views/posts/add_payments.html.haml, app/views/posts/creditCard.html.haml, app/views/posts/mypage.html.haml, app/views/posts/signout.html.haml, app/views/users/edit.html.haml, app/views/users/edit_address.html.haml, config/routes.rb
#What
・各種ページリンク変更(urlからではなく、サイドバーから飛んでください。)
・User編集機能追加(nickname, introductionのみ)、(マイページ->プロフィール)
・ログイン/ログアウトでtoppage-headerの条件分岐
=> added user edit function, updated toppage-header

app/assets/stylesheets/_add_payments.scss, app/assets/stylesheets/_creditCard.scss, app/assets/stylesheets/_edit_address.scss, app/assets/stylesheets/_sidebar.scss, app/assets/stylesheets/_toppage-header.scss, app/assets/stylesheets/mixin/_form.scss, app/assets/stylesheets/signout.scss, app/assets/stylesheets/user.mypage.scss, app/assets/stylesheets/user.profile.scss, app/views/layouts/_exhibit-header.html.haml, app/views/layouts/_toppage-header.html.haml
#What
・サイドバーを使ったビューについて、本番環境で右寄りになる不具合を修正
・toppage-headerのレイアウト変更。
=> modified view layout using sidebar

app/assets/javascripts/addresses.coffee, app/assets/stylesheets/application.scss, app/assets/stylesheets/images.scss, app/assets/stylesheets/items.scss, app/assets/stylesheets/sessions.scss, app/assets/stylesheets/signup.scss, app/assets/stylesheets/sns_credentials.scss, app/assets/stylesheets/users.scss, app/controllers/addresses_controller.rb, app/helpers/addresses_helper.rb, app/views/addresses/edit.html.haml, app/views/layouts/_sidebar.html.haml, config/routes.rb, spec/controllers/addresses_controller_spec.rb, spec/helpers/addresses_helper_spec.rb
#What
・住所編集機能追加 (マイページ -> 本人情報)
・各種リンク変更 (サイドバーからアクセスください。)
=> added address edit function

app/assets/javascripts/signup1.js, app/assets/javascripts/signup2.js, app/assets/javascripts/signup3.js, app/assets/javascripts/signup4.js, app/assets/stylesheets/_signup3.scss, app/controllers/signup_controller.rb, app/models/user.rb, app/views/signup/signup1.html.haml, app/views/signup/signup2.html.haml, app/views/signup/signup3.html.haml
#What
・signupの各ビューで、入力不備がある場合に遷移出来ない用、JSを設定。
　(signup1.js~4.js)
#Why
・UX向上のため
=> added validation on each signup view

app/controllers/items_controller.rb, app/views/items/edit.html.haml
What
出品機能と合わせて実装していきたいため一旦マージします
=> viewの作成、パラメータの取得

app/assets/javascripts/signin.js, app/assets/javascripts/signup1.js, app/assets/javascripts/signup3.js, app/assets/stylesheets/_new.scss, app/assets/stylesheets/_signout_btn.scss, app/assets/stylesheets/_signup0.scss, app/assets/stylesheets/_signup1.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/mixin/_form.scss, app/views/devise/registrations/new.html.haml, app/views/devise/sessions/new.html.haml, app/views/layouts/_sidebar.html.haml, app/views/layouts/_toppage-header.html.haml
#What
　・各種ボタン上でのカーソル表示変更
　・ログイン画面でのリキャプチャ有効化
#Why
　・UX向上のため
=> upgraded UX

app/assets/stylesheets/items.show.scss, app/controllers/items_controller.rb, app/views/items/show.html.haml
#What 
　・商品詳細表示機能の実装(/items/show)
=> added item show function

app/controllers/items_controller.rb, app/views/items/show.html.haml
#What
　商品詳細表示機能の実装 (メンターレビュー用プルリクエスト)
#Why
　以下タスク完了のため
　【サーバサイド】商品詳細表示
=> completed item show function

app/assets/stylesheets/gretel.scss, app/views/items/show.html.haml, config/breadcrumbs.rb
What
パンくずリストの追記
条件分岐の修正
Why
ログインしていない状態で商品詳細ページにアクセスできなかたため
=> 商品詳細ページの修正

app/assets/stylesheets/application.scss, app/assets/stylesheets/cards/_show.scss, app/views/cards/show.html.haml
What
クレジットカード詳細ページの画面実装
Why
クレジットカード登録後の登録カード詳細の確認のため
=> Credit card show

app/assets/stylesheets/gretel.scss, app/views/layouts/_gretel.html.haml, config/breadcrumbs.rb
What
パンくずリストの修正
Why
viewに反映されていなかったため
=> revise-gretel

app/views/layouts/_gretel.html.haml, config/breadcrumbs.rb
What
ログアウト状態でエラーが出ているため一旦マージします
=> Revise gretel

app/controllers/items_controller.rb, app/views/items/buy_confirm.html.haml, app/views/items/show.html.haml, config/deploy.rb
カード未保有が購入確認画面を閲覧しようとした場合、カード登録画面に遷移するよう実装
カード削除機能の実装に対応するため。
=> 購入確認画面におけるカード未保有者のリダイレクト

.gitignore, app/assets/stylesheets/items/_index.scss, app/controllers/cards_controller.rb
#What
　・card_controller.rbの変更
　　- カード削除機能で、Pay.jpの登録情報も削除するよう変更。
　　- カード登録機能での、不具合改善(formのsubmitではなく、JSのsubmitにのみ反応するようif文を追加)
=> updated card_controller.rb

app/assets/stylesheets/items/_index.scss, app/assets/stylesheets/layouts/_footer-icon.scss, app/assets/stylesheets/layouts/_toppage-footer.scss, app/controllers/addresses_controller.rb, app/controllers/application_controller.rb, app/controllers/items_controller.rb, app/controllers/signup_controller.rb, app/controllers/users_controller.rb, app/views/users/mypage.html.haml
#What
　・コントローラのリファクタリング(不要なメソッド、改行を削除)
=> refoctored controllers

app/assets/stylesheets/items/_new.scss, app/controllers/items_controller.rb, app/views/items/exhibiting.html.haml, app/views/layouts/_sidebar.html.haml
=> Sidebar link shuusei

app/assets/javascripts/_item_edit.js, app/assets/javascripts/exhibiting.js, app/assets/stylesheets/items/_edit.scss, app/helpers/addresses_helper.rb, app/helpers/cards_helper.rb, app/helpers/images_helper.rb, app/helpers/items_helper.rb, app/helpers/posts_helper.rb, app/helpers/signup_helper.rb, app/helpers/sns_credentials_helper.rb, app/helpers/users_helper.rb, app/views/items/edit.html.haml, app/views/items/show.html.haml
=> modified items/edit.html.haml

app/assets/javascripts/signup1.js, app/assets/javascripts/signup2.js, app/controllers/signup_controller.rb, app/views/signup/signup1.html.haml, app/views/signup/signup2.html.haml
#What
　新規ユーザー登録時、登録済のメールアドレス/電話番号を入力した際、javascriptにて検出、アラート表示。
=> added javascript inspecting registered email/phone_number

app/assets/javascripts/signup2.js, app/views/items/show.html.haml, app/views/users/exhibiting.html.haml
#What
　"詳細ページ"、"マイページ/出品した商品" の表示不具合を修正
　
=> just modified errors

app/controllers/items_controller.rb
#What
　items_controllerのbefore actionを修正。自分が出品した商品でも、購入済のものは、編集、削除できないよう制限を追加。
=> updated before action "owner-check"

app/assets/javascripts/items_new.js, app/controllers/items_controller.rb
商品編集時に画像を選択せずに編集ボタンを押すと、jqueryで弾かれる問題を解消
=> edit_item_edit
